[package]
name = "winevtx"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "High-performance Windows Event Log query and EVTX parser for Python built with Rust and PyO3"
repository = "https://github.com/ezer-mackenzie/winevtx"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_winevtx"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.29.3", features = ["extension-module"] }
pythonize = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
evtx = { version = "0.12.3", default-features = false, features = ["multithreading"] }
roxmltree = "0.21.1"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.61"
features = [
    "Win32_Foundation",
    "Win32_System_EventLog",
]
